name: Deploy Notes Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code safely
        run: |
          cd /home/motherbloodss/Desktop/notes
          git fetch origin
          git reset --hard origin/main

      - name: Create Backend Env
        run: echo "${{ secrets.NOTES_BE_ENV }}" > /home/motherbloodss/Desktop/notes/notes-be/.env

      - name: Create Frontend Env
        run: echo "${{ secrets.NOTES_FE_ENV }}" > /home/motherbloodss/Desktop/notes/notes-fe/.env

      - name: Ensure network exists
        run: docker network inspect n8n-network >/dev/null 2>&1 || docker network create n8n-network

      - name: Build Backend
        run: |
          docker build \
            --cache-from notes-be:latest \
            -t notes-be:latest \
            /home/motherbloodss/Desktop/notes/notes-be

      - name: Restart Backend
        run: |
          docker rm -f notes-api || true

          docker run -d \
            --name notes-api \
            -p 3003:3003 \
            --restart unless-stopped \
            --network n8n-network \
            --env-file /home/motherbloodss/Desktop/notes/notes-be/.env \
            notes-be:latest

      - name: Build Frontend
        run: |
          docker build \
            --cache-from notes-fe:latest \
            -t notes-fe:latest \
            /home/motherbloodss/Desktop/notes/notes-fe

      - name: Restart Frontend
        run: |
          docker rm -f notes || true

          docker run -d \
            --name notes \
            -p 5174:5174 \
            --restart unless-stopped \
            --network n8n-network \
            notes-fe:latest

      - name: Cleanup Env Files
        if: always()
        run: |
          rm -f /home/motherbloodss/Desktop/notes/notes-be/.env
          rm -f /home/motherbloodss/Desktop/notes/notes-fe/.env
